spring:
  application:
    name: product-server
  datasource:
    url: jdbc:mysql://localhost:3306/learning?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
